export { default as Navbar } from "./Navbar/Navbar";
export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as MenShoes } from "./MenShoes/MenShoes";
export { default as MenShoesDetails } from "./MenShoesDetails/MenShoesDetails";
export { default as WomenShoes } from "./WomenShoes/WomenShoes";
export { default as WomenShoesDetails } from "./WomenShoesDetails/WomenShoesDetails";
export { default as ContactUs } from "./ContactUs/ContactUs";
export { default as Footer } from "./Footer/Footer";
